#!/usr/bin/env python3
"""
Phần 1 — Việc 1: Repository Cloning & File Discovery
=====================================================
Liệt kê toàn bộ file .py trong repo huggingface/accelerate, loại bỏ các file
test / setup / auto-generated theo tiêu chí rõ ràng, đếm tổng số và lưu JSON.

Chạy:
    python scripts/discover_files.py --repo accelerate --out output/file_discovery.json
"""

from __future__ import annotations

import argparse
import json
import re
from datetime import datetime, timezone
from pathlib import Path


# --------------------------------------------------------------------------- #
# TIÊU CHÍ LOẠI BỎ (exclusion criteria) — mỗi rule trả về True nếu file bị loại
# --------------------------------------------------------------------------- #

# Marker thường gặp trong header của file auto-generated
_AUTOGEN_MARKERS = (
    "auto-generated",
    "autogenerated",
    "automatically generated",
    "do not edit",
    "do not modify",
    "@generated",
    "generated by",
    "this file is generated",
)


def is_test_file(rel_parts: tuple[str, ...], name: str) -> bool:
    """File test: nằm trong thư mục tests/ hoặc tên theo convention pytest/unittest."""
    if "tests" in rel_parts or "test" in rel_parts:
        return True
    if name == "conftest.py":
        return True
    if name.startswith("test_") or name.endswith("_test.py"):
        return True
    return False


def is_setup_file(rel_parts: tuple[str, ...], name: str) -> bool:
    """File setup / build / packaging (không phải source logic của repo)."""
    setup_names = {"setup.py", "_setup.py"}
    return name in setup_names


def is_autogenerated_file(path: Path, name: str) -> bool:
    """
    File auto-generated: theo tên (versioning, protobuf) HOẶC theo marker trong
    ~40 dòng đầu (vd '# DO NOT EDIT', '# @generated').
    """
    # 1) Theo tên file
    if name in {"_version.py", "version.py", "_generated.py"}:
        return True
    if name.endswith(("_pb2.py", "_pb2_grpc.py")):  # protobuf
        return True

    # 2) Theo marker trong header
    try:
        with path.open("r", encoding="utf-8", errors="ignore") as fh:
            head_lines = []
            for _ in range(40):
                line = fh.readline()
                if not line:
                    break
                head_lines.append(line)
            head = "".join(head_lines)
    except OSError:
        head = ""
    head_lower = head.lower()
    return any(marker in head_lower for marker in _AUTOGEN_MARKERS)


def classify(path: Path, repo_root: Path) -> dict:
    """Phân loại 1 file .py -> record với lý do loại bỏ (nếu có)."""
    rel = path.relative_to(repo_root)
    rel_parts = rel.parts
    name = path.name

    reasons: list[str] = []
    if is_test_file(rel_parts, name):
        reasons.append("test")
    if is_setup_file(rel_parts, name):
        reasons.append("setup")
    if is_autogenerated_file(path, name):
        reasons.append("auto-generated")

    return {
        "path": rel.as_posix(),
        "size_bytes": path.stat().st_size,
        "excluded": bool(reasons),
        "exclude_reasons": reasons,
    }


def discover(repo_root: Path) -> dict:
    all_py = sorted(repo_root.rglob("*.py"))
    records = [classify(p, repo_root) for p in all_py]

    kept = [r for r in records if not r["excluded"]]
    excluded = [r for r in records if r["excluded"]]

    # Thống kê lý do loại bỏ
    reason_counts: dict[str, int] = {}
    for r in excluded:
        for reason in r["exclude_reasons"]:
            reason_counts[reason] = reason_counts.get(reason, 0) + 1

    return {
        "repository": "huggingface/accelerate",
        "clone_command": "git clone --depth 1 https://github.com/huggingface/accelerate.git",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "exclusion_criteria": {
            "test": "Nằm trong thư mục tests/ hoặc tên khớp test_*.py / *_test.py / conftest.py",
            "setup": "File packaging/build: setup.py",
            "auto-generated": "Tên _version.py/version.py/*_pb2.py HOẶC header (40 dòng đầu) chứa marker như 'DO NOT EDIT', '@generated', 'auto-generated'",
        },
        "summary": {
            "total_py_files": len(records),
            "kept_files": len(kept),
            "excluded_files": len(excluded),
            "excluded_by_reason": reason_counts,
        },
        "kept_files": [r["path"] for r in kept],
        "excluded_files": [
            {"path": r["path"], "reasons": r["exclude_reasons"]} for r in excluded
        ],
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Discover .py files in a repo")
    parser.add_argument("--repo", default="accelerate", help="Đường dẫn repo đã clone")
    parser.add_argument(
        "--out", default="output/file_discovery.json", help="File JSON đầu ra"
    )
    args = parser.parse_args()

    repo_root = Path(args.repo).resolve()
    if not repo_root.is_dir():
        raise SystemExit(f"[ERROR] Không tìm thấy repo: {repo_root}")

    result = discover(repo_root)

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(result, indent=2, ensure_ascii=False), encoding="utf-8")

    s = result["summary"]
    print("=" * 60)
    print("  FILE DISCOVERY — huggingface/accelerate")
    print("=" * 60)
    print(f"  Tổng số file .py tìm được : {s['total_py_files']}")
    print(f"  Giữ lại (source thật)     : {s['kept_files']}")
    print(f"  Loại bỏ                   : {s['excluded_files']}")
    for reason, cnt in sorted(s["excluded_by_reason"].items()):
        print(f"      - {reason:<16}: {cnt}")
    print("-" * 60)
    print(f"  Đã lưu JSON -> {out_path}")
    print("=" * 60)


if __name__ == "__main__":
    main()
